import { Component, Input } from '@angular/core';
import { Permit } from '../../interfaces/models';

@Component({
  selector: 'app-permit-document',
  template: `
    <div id="permit-document-export" class="permit-doc" *ngIf="permit">
      <div class="permit-header">
        <div class="brand">
          <ion-icon name="shield-checkmark"></ion-icon>
          <div>
            <h1>DigiPermit</h1>
            <p>Compliance Monitoring Record</p>
          </div>
        </div>
        <div class="doc-type">{{ permit.permit_types?.name || 'Immigration Document' }}</div>
      </div>

      <div class="banner">NOT AN OFFICIAL GOVERNMENT IMMIGRATION PERMIT</div>

      <div class="permit-body">
        <div class="details">
          <div class="field"><span>Full name</span><strong>{{ permit.foreign_nationals?.full_name }}</strong></div>
          <div class="field"><span>Nationality</span><strong>{{ permit.foreign_nationals?.nationality || '—' }}</strong></div>
          <div class="field"><span>Passport no.</span><strong>{{ maskPassport(permit.passport_number) }}</strong></div>
          <div class="field"><span>Permit no.</span><strong>{{ permit.permit_number }}</strong></div>
          <div class="field"><span>Organisation</span><strong>{{ permit.organisations?.name || '—' }}</strong></div>
          <div class="field"><span>Issue date</span><strong>{{ permit.issue_date }}</strong></div>
          <div class="field"><span>Expiry date</span><strong>{{ permit.expiry_date }}</strong></div>
          <div class="field"><span>Status</span><strong class="status">{{ permit.status | titlecase }}</strong></div>
        </div>
        <div class="qr-section">
          <p class="scan-text">Scan to verify</p>
          <app-qr-display [value]="permit.qr_code_value" [showValue]="false"></app-qr-display>
          <p class="rfid" *ngIf="permit.rfid_tag">RFID: {{ permit.rfid_tag }}</p>
        </div>
      </div>

      <div class="permit-footer">
        <p>This document is generated by DigiPermit for compliance monitoring and verification purposes only.
        Official visas and permits are issued only by the relevant government authority.</p>
        <p class="doc-id">Record ID: {{ permit.id }}</p>
      </div>
    </div>
  `,
  styles: [`
    .permit-doc {
      max-width: 720px; margin: 0 auto; background: #fff; border: 2px solid #2d6a4f;
      border-radius: 12px; overflow: hidden; box-shadow: 0 8px 32px rgba(0,0,0,0.12);
      font-family: 'Segoe UI', system-ui, sans-serif; color: #1a1a1a;
    }
    .permit-header {
      display: flex; justify-content: space-between; align-items: flex-start;
      padding: 20px 24px; background: linear-gradient(135deg, #1b4332, #2d6a4f); color: #fff;
    }
    .brand { display: flex; gap: 12px; align-items: center; }
    .brand ion-icon { font-size: 40px; }
    .brand h1 { margin: 0; font-size: 1.4rem; font-weight: 800; }
    .brand p { margin: 0; font-size: 0.75rem; opacity: 0.9; }
    .doc-type { font-size: 0.85rem; font-weight: 600; text-align: right; max-width: 140px; }
    .banner {
      background: #fff3e0; color: #e65100; text-align: center; font-size: 0.7rem;
      font-weight: 700; letter-spacing: 0.05em; padding: 8px;
    }
    .permit-body { display: flex; flex-wrap: wrap; padding: 24px; gap: 24px; }
    .details { flex: 1; min-width: 240px; }
    .field { margin-bottom: 12px; border-bottom: 1px solid #eee; padding-bottom: 8px; }
    .field span { display: block; font-size: 0.7rem; color: #666; text-transform: uppercase; letter-spacing: 0.04em; }
    .field strong { font-size: 1rem; }
    .field strong.status { color: #2d6a4f; }
    .qr-section { text-align: center; min-width: 200px; }
    .scan-text { font-size: 0.85rem; color: #2d6a4f; font-weight: 600; margin: 0 0 8px; }
    .rfid { font-family: monospace; font-size: 0.7rem; color: #888; margin-top: 8px; }
    .permit-footer {
      background: #f5f5f5; padding: 16px 24px; font-size: 0.65rem; color: #666; line-height: 1.5;
    }
    .doc-id { margin: 8px 0 0; font-family: monospace; }

    @media print {
      .permit-doc { box-shadow: none; border: 2px solid #000; max-width: 100%; }
    }
  `],
  standalone: false,
})
export class PermitDocumentComponent {
  @Input() permit!: Permit;

  maskPassport(p: string): string {
    if (!p || p.length < 4) return '****';
    return p.slice(0, 2) + '*'.repeat(Math.max(p.length - 4, 3)) + p.slice(-2);
  }
}
